### ISSUE TITLE
tasks before tuesday

### ISSUE THREAD

**Issue by 1Valeria** [NCMINSKTRAININGS/team_01#3]
Дописываем entity и dao, заливаем в develop. Проверю и замерджу в мастер как только закончим.
Стас, ты заливал к себе на ветку мою часть энтити, - я исправила баги, обнови.

**Comment by PetrusHahol** [comment]
Доправляй баги)

**Comment by PetrusHahol** [comment]
Мержанем просто правильно, всё ок
